# nonk8s
apiVersion: "backstage.io/v1alpha1"
kind: "Component"
metadata:
  name: "prodspek_elveg"
  tags:
  - "public"
spec:
  type: "documentation"
  lifecycle: "production"
  owner: "felles_kartdatabase"
  system: "standardisering"
